travis:
  secure:
    BINSTAR_TOKEN: VbVeetLji1KPpNriJNu3nqrSWnVv6MqyAugsf7EDhDao/C/eBjXQt95g33p13dPI8CDgjjtaEXNhgPWFJLjikZrkxYcfYbpoh8sdCwz+sFk+i984888dNWQ1m2x0+tJeUE9Z8rAY+yYkUfMgzAf98EEGheAg5DuPg/G/RarhAvmR6uUyc51r/R7eMqBX+XUobglv5QH+yrqtyFwD5evPiUmfFxwZa4HdSh1rtbMU+tMl4dlAS/OVQBVUqUxGLANXF5vU5fihBhFx5dnUsfVRVpiF+dB3xJjsqmrxeX+sMWoxGayDiruUEczI/usnAolr2wp937ANTIy2dP+5E9zXRV0zOAUPT1tfMLZWzJNDxnuv9oK8vwnn1yl29CsgDobOulSGsTzWwA1zkShcL4jNsQT8uPGpCQs/vBJZwcGlwQ02D7gH9Mx1RBsWKtFdvqe2wvVbIAJna+HWyk3fNbvZPGvM+lCeewtvulLvf0JyRfUgygrFToJJQ9AztE2xLpfdSWMC1C+w1/tkSl8tlnvQO/JHVyq+pbKAzZTowgH1mVDRWLaJCZuB0LH+nL5I8QUknyPIDoZtNCGoQ0HkBb4RSrvhR1APk2atfsMDVDk0nSQu/Ccmwi8Qh0bYmgx/a+TSkm7Y98YWLzdrOjUdElP2eUzc3QJXSYKZV2T4fJM2uQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
